#ifndef NDRSTATECATEGORIES_H
#define NDRSTATECATEGORIES_H

typedef enum NDR_StateCategories{
    INVALID, ACCEPT, IGNORE, ERROR, STARTSTATE, ALLOWSTATE, ESCAPESTATE, ENDSTATE, KEYWORD, LITERAL, STATES, ITEMS, SETTING, NOTAPPLICABLE
} NDR_StateCategories;

#endif
